# Generated by Django 4.2.1 on 2023-05-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(unique=True),
        ),
    ]
