# Generated by Django 4.2.1 on 2023-05-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='post_code_zip',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
