# Generated by Django 4.2.1 on 2023-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_location_post_code_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='currenct_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='currenct_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
