# Generated by Django 4.2.1 on 2023-05-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_currenct_lat_truck_current_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='post_code_zip',
            new_name='zip_code',
        ),
    ]
